require("prototypes.fluidic-energy")
require("prototypes.fluidic-transformers")
require("prototypes.fluidic-poles")
require("prototypes.fluidic-accumulator")
require("prototypes.fluidic-power-switch")
require("prototypes.fluidic-energy-meter")
require("prototypes.fluidic-technology")